version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  curl-jq:
    image: curl-jq:local
    pull_policy: build
    build:
      context: ./traefik
      dockerfile: Dockerfile.jq
    restart: "no"
    profiles: [ "tools" ]

  ssv-dkg-operator:
    restart: "unless-stopped"
    image: bloxstaking/ssv-dkg:${SSV_DKG_TAG:-latest}
    ports:
      - "3030:3030"
    <<: *logging
    command: start-operator --outputPath /output --configPath /config/operator.yaml
    volumes:
      - ./ssv-config/:/config
      - ./ssv-config/dkg-output:/output
