scrape_configs:
  - job_name: obol-node
    metrics_path: /metrics
    static_configs:
      - targets:
        - obol-node:3620
  - job_name: validator-ejector
    metrics_path: /metrics
    static_configs:
      - targets:
        - validator-ejector:8989